### ISSUE TITLE
setup.py does not include package data

### ISSUE THREAD

**Issue by dannygoldstein** [ZwickyTransientFacility/ztf_sim#2]
After doing a fresh install following the instructions in the readme, I get:

```
(ztf_sim_test) dhcp-194-201:~ danny$ run_ztf_sim --help
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Traceback (most recent call last):
  File "/anaconda2/envs/ztf_sim_test/bin/run_ztf_sim", line 6, in <module>
    from ztf_sim.simulate import simulate
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/__init__.py", line 5, in <module>
    from .Scheduler import *
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/Scheduler.py", line 6, in <module>
    from .QueueManager import ListQueueManager, GreedyQueueManager, GurobiQueueManager
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/QueueManager.py", line 14, in <module>
    from .magnitudes import limiting_mag
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/magnitudes.py", line 19, in <module>
    R20_interp_alt = {1: interp_R20_airmass(filter_id=1),
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/magnitudes.py", line 14, in interp_R20_airmass
    data = np.loadtxt(R20_file)
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/numpy/lib/npyio.py", line 962, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /anaconda2/envs/ztf_sim_test/lib/python3.7/site-packages/ztf_sim/../data/R20_absorbed_ZTFg.txt not found.
(ztf_sim_test) dhcp-194-201:~ danny$
```

**Comment by ebellm** [comment]
Sorry I didn't see this much sooner--turns out I wasn't watching the repository, and didn't get notified of the issue...

For setuptools-related reasons I am too lazy to dig into further, it appears one can work around this by simply using the "editable" pip installation:

`pip install -e git+https://github.com/ZwickyTransientFacility/ztf_sim.git#egg=ztf_sim`

I've updated the README accordingly.
